### ISSUE TITLE
Products seem to be changing number when back in stock

### ISSUE THREAD

**Issue by DroidCry** [spoji/SQDC-Out-of-Stock-Notification#2]
I was subscribed to get a notify from this https://www.sqdc.ca/en-CA/p-blue-dream/629108018061-P/629108017064
But the product now back in stock is this page
https://www.sqdc.ca/en-CA/p-blue-dream/629108018146-P/629108018146

**Comment by spoji** [comment]
Thank you for opening this issue DroidCry!

It would seem SQDC changed the sku of the product from 629108017064 to 629108018146, which created the issue. The first link you provided shows all sort of errors. For example "The sku is required" inside orckestra.composer.js

I'm not sure how to tackle this issue. I know some people that are familiar with Orckestra. I'll check with them for a solution around this.

**Comment by DroidCry** [comment]
You're welcome. Yeah I figured the sku change was going to mess with what you had. Good luck and thanks for making this.

**Comment by spoji** [comment]
Unfortunately, my friend who knows Orckestra's platform don't have a clue why the sku has been changed.

The only way I see how to address this issue is to warn the users when a tracked product has been "discontinued / removed". While not optimal, this would assure that people can look up again for their product on the website and add back the notification for the new product's sku.

@DroidCry Would this be a proper solution for you?

**Comment by DroidCry** [comment]
Yeah, I think that's definitely better than not knowing.

**Comment by spoji** [comment]
Unfortunately, I wasn't able to find a proper way to fix this issue. The underlying problem is that orphan product pages don't give us good events or errors for content scripts to be alerted. I could listen to HTTP 500 error codes on findInventoryItems calls from the webpage but this would mean adding the webRequest permission in the extension (something I'm not willing to add just to fix this single issue).

I'll continue to monitor those pages for a way in the near future to fix this up properly.
